version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.2

    environment:
      PROJECT_PATH: "~/project"  # Define the project path for analysis

    steps:
      - checkout  # Checkout the source code from the repository

      - run:
          name: "Display PHP and Composer Versions"
          command: |
            php --version
            composer --version

      - run:
          name: "Configure Composer for PHP CodeSniffer"
          command: |
            composer --global config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true

      - run:
          name: "Install Drupal Coder"
          command: |
            composer require drupal/coder --working-dir=.circleci -vvv

      - run:
          name: "Run Drupal Coding Standards Check"
          command: |
            ./.circleci/vendor/bin/phpcs \
              --ignore=./.circleci/* \
              --standard=Drupal,DrupalPractice \
              --extensions=php,module,inc,install,test,profile,theme,css,info,yml,md \
              $PROJECT_PATH

workflows:
  version: 2
  drupal_standards_workflow:
    jobs:
      - build
